### ISSUE TITLE
Json.More.JsonNull missing from JsonLogic.dll

### ISSUE THREAD

**Issue by jevvo-trimble** [gregsdennis/json-everything#290] opened 2022-06-17 09:37 UTC
**Environment**
- Nuget Package: JsonLogic 3.0.0
- Nuget Version: 6.1.0
- OS: WSL
- .Net Target: NET6.0

**Describe the bug**
Json.More.JsonNull missing from JsonLogic.dll
![image](https://user-images.githubusercontent.com/107613400/174270615-7276fbd6-8ac9-4333-b1a3-a8893f57570b.png)

**To Reproduce**
Create NET6 console project only with JsonLogic 3.0.0.
Run this code:

Program.cs
```
namespace TestJsonLogic3
{
    using System.Text.Json.Nodes;
    using Json.Logic;
    using System.Text.Json;

    class Program
    {
        static void Main(string[] args)
        {
            var data = JsonNode.Parse("{\"a\": 1}");
            var rule = JsonSerializer.Deserialize<Rule>("{\"===\": [1, 1]}");
        }
    } 
}
```
csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonLogic" Version="3.0.0" />
  </ItemGroup>  

</Project>
```
**Expected behavior**
Deserialize to rule

**Additional context**
This issue could be fixed by including Json.More.Net.
But does not look right to me.
Please let me know if I'm doing something wrong.
It's working from json-everything unit tests. So I would guess the issue is in nuget package.

**Comment by gregsdennis** [comment] 2022-06-17 09:41
This is a duplicate of #288 and it has already been resolved.  Please use v3.0.1.

**Closed by gregsdennis** 2022-06-17 09:41 UTC
Labels: bug

**Comment by jevvo-trimble** [comment] 2022-06-17 09:46
Sorry about that. The latest in a NuGet is 3.0.0 https://www.nuget.org/packages/JsonLogic/#versions-body-tab

**Comment by gregsdennis** [comment] 2022-06-17 09:48
My apologies.  It looks like some of the tests failed, so it didn't publish the new version.  Give me a few minutes.

**Comment by jevvo-trimble** [comment] 2022-06-17 10:39
Thank you! Working now!
