### ISSUE TITLE
JSON Schema Registry is not thread-safe

### ISSUE THREAD

**Issue by msallin** [gregsdennis/json-everything#503] opened 2023-08-08 10:32 UTC
### Nuget Package

JsonSchema.Net

### Package Version

4.1.8

### Operating System

Linux

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug

Not sure if this is the same with the new version. We are about to update to 5.1.3, as you suggested here.
Can you elaborate if this is known/by design/if you accept contributions?

```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access.
 A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Json.Schema.SchemaRegistry.CheckRegistry(Dictionary`2 lookup, Uri uri)
   at Json.Schema.SchemaRegistry.RegisterSchema(Uri uri, IBaseDocument document)
   at Json.Schema.SchemaRegistry.Register(Uri uri, IBaseDocument document)

Formatted by https://st.elmah.io
```

### Please add test code or steps to reproduce the behavior

Race condition.

### What did you expect?

That it is thread-safe.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment] 2023-08-08 10:34
Thanks for filling.  Can you try with the latest version, please? I suspect the issue is the same since the registry didn't change, but I'd like to be sure.

Also, could you provide reproducing code, please?

**Comment by msallin** [comment] 2023-08-09 06:55
We will work on it. Expect the repro in a few weeks.

**Comment by gregsdennis** [comment] 2023-09-10 21:40
@msallin can you retest this with v5.2.5, please?

**Comment by msallin** [comment] 2023-09-14 08:01
@gregsdennis we will first "test" #502. If it works, we will remove the lock around the schema registry and I'll observe it. We saw the problem around 1x per month.

**Comment by gregsdennis** [comment] 2023-09-14 08:21
That is remarkably infrequent!

**Comment by msallin** [comment] 2023-09-18 14:25
I removed the lock and deployed it. I'll reopen when we discover the problem again.

**Comment by msallin** [comment] 2023-10-09 14:29
We faced the issue again. We will add the lock again but we do not plan to provide a reproduction as we have other prios.
Maybe just declare it as such in the docs or inline comments.

**Comment by jnystad** [comment] 2023-10-16 08:10
We hit an issue in KeywordExtensions where the _keywordNames dictionary is corrupted due to concurrent access.

Shouldn't all the various static dictionaries that are modified after creation be of type ConcurrentDictionary? We generate schemas on demand, which means multiple API requests may trigger this issue on any of the cache dictionaries that are updated at any time.

Otherwise, the entire library should be considered not thread-safe, and we'll have to make some changes to deal with that. This is up to you, of course.

**Comment by gregsdennis** [comment] 2023-10-18 20:31
> KeywordExtensions where the _keywordNames dictionary

This shouldn't change after initialization.  Are you using custom keywords?

> We generate schemas on demand

Are you using _JsonSchema.Net.Generation_ to do this?  We (JSON Schema) generally advises against generating schemas in production.  This kind of generation is useful as a dev tool, but generated schemas should be verified by a dev before being put into production.

**Comment by gregsdennis** [comment] 2023-12-16 00:18
Closing for now.  If the issue is able to be reliably replicated, I'll look into it again.

**Closed by gregsdennis** 2023-12-16 00:18 UTC
Labels: bug, pkg:schema
