### ISSUE TITLE
How to prettyprint generated schema

### ISSUE THREAD

**Issue by MichaelJachan** [gregsdennis/json-everything#266] opened 2022-05-18 14:58 UTC
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.0.1
- OS: Win10
- .Net Target: Core6.0

How to prettyprint/format a generated schema?

OLD:
`{"type":"object","properties":{bla},"additionalProperties":false}`

NEW:
```
{
  "type": "object",
  "properties": {
    bla
  },
  "additionalProperties": false
}
```

**Comment by gregsdennis** [comment] 2022-05-18 18:49
Hello.  This is a duplicate of #229.

Essentially, you just need to provide the right options when serializing.

**Closed** 2022-05-18 18:49 UTC
Labels: question
