### ISSUE TITLE
System.Text.Json.JSonReaderException on valid Json

### ISSUE THREAD

**Issue by erwan-joly** [gregsdennis/json-everything#57] opened 2020-12-18 23:55 UTC
**Describe the bug**
Can not asJsonElement a specific valid JSon

**To Reproduce**
```
"{\"BazaarItem\":{\"Amount\":99,\"BazaarItemId\":0,\"DateStart\":\"2020-12-18T23:44:46.0893914Z\",\"Duration\":3600,\"IsPackage\":false,\"ItemInstanceId\":\"9abf1cd6-25e4-41e5-9353-4be2e80bbab3\",\"MedalUsed\":false,\"Price\":80,\"SellerId\":1},\"ItemInstance\":{\"Amount\":99,\"BoundCharacterId\":null,\"CharacterId\":0,\"Design\":0,\"DurabilityPoint\":0,\"ItemDeleteTime\":null,\"ItemVNum\":0,\"Upgrade\":0,\"Rare\":0,\"Id\":\"9abf1cd6-25e4-41e5-9353-4be2e80bbab3\"},\"SellerName\":\"test\"}".AsJsonElement()
```

"'B' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 3."

**Expected behavior**
I think this should return a valid JsonElement.
 
**Desktop (please complete the following information):**
 - OS: Win 10
- .Net 5
 - Nuget Version JSonPatch.Net 1.0.1

**Comment by gregsdennis** [comment] 2020-12-18 23:57
This is a duplicate of https://github.com/gregsdennis/json-everything/issues/51.

`.AsJsonElement` converts _objects_ into `JsonElement`s.  It's not a shortcut for parsing.

**Closed by gregsdennis** 2020-12-18 23:57 UTC
Labels: duplicate
