### ISSUE TITLE
JsonLogic - unexpected result after evaluating rule

### ISSUE THREAD

**Issue by JanKnipp** [gregsdennis/json-everything#183] opened 2021-11-14 09:28 UTC
**Environment**
- Nuget Package: JsonLogic
- Nuget Version: 1.3.2
- OS: Windows
- .Net Target: Net5.0

**Describe the bug**
JsonLogic does not produce the same output as jsonlogic.com/play.html
Your playground also differs (as it's using the library) https://json-everything.net/json-logic

**To Reproduce**
Rule:
```json
{
  "if": [
    {
      "var": "data.sub"
    },
    {
      "===": [
        {
          "var": "data.sub.0.element"
        },
        "12345"
      ]
    },
    true
  ]
}
```

Data:
```json
{
   "data": {
    "sub": [
      {
        "element": "12345"
      }
    ]
  }
}
```

==> Result is truthy. Adding a different data to the data.sub.0.element field should result in falsy.

Rule:
```json
{
  "if": [
    {
      "var": "data.sub"
    },
    {
      "===": [
        {
          "var": "data.sub.0.element"
        },
        "12345"
      ]
    },
    true
  ]
}
```

Data:
```json
{
   "data": {
    "sub": [
      {
        "element": "12346"
      }
    ]
  }
}
```

Shows no result on the playground page (https://json-everything.net/json-logic) and throws an exception in .net code.

**Expected behavior**
Result should be falsy in the second example (in case I'm getting how jsonlogic works, which I'm not sure about).
The playground on https://jsonlogic.com/play.html shows the output as false

Thanks

**Comment by gregsdennis** [comment] 2021-11-15 05:55
Thanks for this report.  I'll get a unit test set up to reproduce.

**Comment by gregsdennis** [comment] 2021-11-15 06:16
I can't get this to fail, either in a test or on the website.  I _do_ see the "no response" you're talking about, but that's something in the website, not in the API or the library.  The API returns `{"result":false,"errors":null}` for the second scenario, which is correct.

Both of your scenarios work for me.  I've uploaded the tests in branch `issue-183-rule-eval-wrong` so that you can see them.

**Comment by gregsdennis** [comment] 2021-11-19 20:19
@JanKnipp is there any more context you can add to this, or were you just having problems with the website?

**Comment by JanKnipp** [comment] 2021-11-23 15:12
Sorry, took me a while to respond. I guess I tried to strip down the case and focused too much on the two websites :(

Please see this case:

Rule

> {"and":[{"if":[{"var":"data.r.0"},{"in":[{"var":"data.r.0.tg"},["140539006"]]},true]},{"if":[{"var":"data.t.0"},{"in":[{"var":"data.t.0.tg"},["140539006"]]},true]},{"if":[{"var":"data.v.0"},{"in":[{"var":"data.v.0.tg"},["140539006"]]},true]}]}

Data

> {"data":{"r":[{"tg":"140539006"}],"t":[{"tg":"140539006"}],"v":[{"tg":"Test"}]}}

```
[Test]
        public void Issue183_RuleEvaluatesWrong2_Falsy()
        {
            var jsonRule = "{\"and\":[{\"if\":[{\"var\":\"data.r.0\"},{\"in\":[{\"var\":\"data.r.0.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.t.0\"},{\"in\":[{\"var\":\"data.t.0.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.v.0\"},{\"in\":[{\"var\":\"data.v.0.tg\"},[\"140539006\"]]},true]}]}";
            var logic = JsonDocument.Parse(jsonRule);
            var rule = JsonSerializer.Deserialize<Rule>(logic.RootElement.ToJsonString());


            var data = JsonDocument.Parse("{\"data\":{\"r\":[{\"tg\":\"140539006\"}],\"t\":[{\"tg\":\"140539006\"}],\"v\":[{\"tg\":\"Test\"}]}}");

            var result = rule.Apply(data.RootElement);

            JsonAssert.AreEquivalent(false, result);
        }
```

This will throw an exception as the JsonValueKind is of type object which has not been implemented yet.


> Json.Logic.JsonLogicException
>   HResult=0x80131500
>   Message=Cannot determine truthiness of `Object`.
>   Source=JsonLogic
>   StackTrace:
>    at Json.Logic.JsonElementExtensions.IsTruthy(JsonElement element) in json-everything\JsonLogic\JsonElementExtensions.cs:line 39
>    at Json.Logic.Rules.IfRule.Apply(JsonElement data) in json-everything\JsonLogic\Rules\IfRule.cs:line 42
>    at Json.Logic.Rules.AndRule.<>c__DisplayClass2_0.<Apply>b__0(Rule i) in json-everything\JsonLogic\Rules\AndRule.cs:line 21
>    at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
>    at Json.Logic.Rules.AndRule.Apply(JsonElement data) in json-everything\JsonLogic\Rules\AndRule.cs:line 23
>    at Json.Logic.Tests.GithubTests.Issue183_RuleEvaluatesWrong2_Falsy() in json-everything\JsonLogic.Tests\GithubTests.cs:line 72


Sorry for the confusion
Jan

**Comment by JanKnipp** [comment] 2021-11-23 16:11
Another testcase that actually runs but resolves in an unexpected result

Rule:

> {"===":[{"reduce":[[{"var":"data.r"},{"var":"data.t"},{"var":"data.v"}],{"\u002B":[{"var":"accumulator"},{"if":[{"var":"current.0"},1,0]}]},0]},1]}

Data:

> {"data":{"r":[{"tg":"140539006"},{"tg":"140539006"}]}}

Expected outcome: true
Actual outcome: false

```
[Test]
        public void Issue183_RuleEvaluatesWrong3_Falsy()
        {
            var jsonRule = "{\"===\":[{\"reduce\":[[{\"var\":\"data.r\"},{\"var\":\"data.t\"},{\"var\":\"data.v\"}],{\"\\u002B\":[{\"var\":\"accumulator\"},{\"if\":[{\"var\":\"current.0\"},1,0]}]},0]},1]}";
            var logic = JsonDocument.Parse(jsonRule);
            var rule = JsonSerializer.Deserialize<Rule>(logic.RootElement.ToJsonString());


            var data = JsonDocument.Parse("{\"data\":{\"r\":[{\"tg\":\"140539006\"},{\"tg\":\"140539006\"}]}}");

            var result = rule.Apply(data.RootElement);

            JsonAssert.AreEquivalent(true, result);
        }
```

**Comment by gregsdennis** [comment] 2021-11-24 06:35
So apparently object truthiness isn't implemented because [their docs](https://jsonlogic.com/truthy.html) don't have it.

I've opened https://github.com/jwadhams/json-logic/issues/34 to find out what to do here.

**Comment by JanKnipp** [comment] 2021-11-24 07:06
```
[Test]
        public void Issue183_RuleEvaluateFailArray()
        {
            var jsonRule = "{\"and\":[{\"if\":[{\"var\":\"data.r.0\"},{\"in\":[{\"var\":\"data.r.0.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.t.0\"},{\"in\":[{\"var\":\"data.t.0.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.v.0\"},{\"in\":[{\"var\":\"data.v.0.tg\"},[\"140539006\"]]},true]}]}";
            var logic = JsonDocument.Parse(jsonRule);
            var rule = JsonSerializer.Deserialize<Rule>(logic.RootElement.ToJsonString());

            var data = JsonDocument.Parse("{\"data\":{\"r\":[{\"tg\":\"140539006\"}],\"t\":[{\"tg\":\"140539006\"}],\"v\":[{\"tg\":\"Test\"}]}}");

            var result = rule.Apply(data.RootElement);

            JsonAssert.AreEquivalent(true, result);
        }
```

When the array is changed to a simple object it will pass again.
Process fails when the content is **ValueKind = Object : "{"tg":"140539006"}"**
but it seems to work fine when this is a single number.

```
        [Test]
        public void Issue183_RuleEvaluateNonArray()
        {
            var jsonRule = "{\"and\":[{\"if\":[{\"var\":\"data.r.0\"},{\"in\":[{\"var\":\"data.r.0.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.t.0\"},{\"in\":[{\"var\":\"data.t.0.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.v.0\"},{\"in\":[{\"var\":\"data.v.0.tg\"},[\"140539006\"]]},true]}]}";
            var logic = JsonDocument.Parse(jsonRule);
            var rule = JsonSerializer.Deserialize<Rule>(logic.RootElement.ToJsonString());

            var data = JsonDocument.Parse("{\"data\":{\"r\":{\"tg\":\"140539006\"},\"t\":{\"tg\":\"140539006\"},\"v\":{\"tg\":\"Test\"}}}");
            var result = rule.Apply(data.RootElement);

            JsonAssert.AreEquivalent(true, result);
        }
```

**Comment by gregsdennis** [comment] 2021-11-24 07:41
Yeah, this is all due to the system not knowing how to interpret truthiness for an object.

**Comment by JanKnipp** [comment] 2021-11-24 08:14
In the end my second testcase (_Issue183_RuleEvaluateNonArray()_) was incorrect as i was still using the json-path  which targeted for the first element in the array (data.r.0 instead of data.r) and in the end was only resulting in getting a null value.

When correcting the "working" testcase it also fails now. I was wondering why it succeeded as it should still have been an object.

```
[Test]
        public void Issue183_RuleEvaluateNonArray2()
        {
            var jsonRule = "{\"and\":[{\"if\":[{\"var\":\"data.r\"},{\"in\":[{\"var\":\"data.r.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.t\"},{\"in\":[{\"var\":\"data.t.tg\"},[\"140539006\"]]},true]},{\"if\":[{\"var\":\"data.v\"},{\"in\":[{\"var\":\"data.v.tg\"},[\"140539006\"]]},true]}]}";
            var logic = JsonDocument.Parse(jsonRule);
            var rule = JsonSerializer.Deserialize<Rule>(logic.RootElement.ToJsonString());

            var data = JsonDocument.Parse("{\"data\":{\"r\":{\"tg\":\"140539006\"},\"t\":{\"tg\":\"140539006\"},\"v\":{\"tg\":\"Test\"}}}");
            var result = rule.Apply(data.RootElement);

            JsonAssert.AreEquivalent(true, result);
        }
```

Thanks

**Comment by gregsdennis** [comment] 2021-12-05 00:08
Still waiting on a response from JSON Logic.  Sorry this is taking a while.

**Comment by JanKnipp** [comment] 2021-12-07 18:52
Hi,

no problem - thanks a lot for investigating the issue.

I was able to solve some of my issues by playing around with your code and adding the JsonValueKind for objects to the IsTruthy method, but as you said, we're not sure if this intended behaviour.

```
public static bool IsTruthy(this JsonElement element)
		{
			return element.ValueKind switch
			{
				JsonValueKind.Array => element.GetArrayLength() != 0,
				JsonValueKind.String => element.GetString() != string.Empty,
				JsonValueKind.Number => element.GetDecimal() != 0,
				JsonValueKind.True => true,
				JsonValueKind.False => false,
				JsonValueKind.Null => false,
				JsonValueKind.Object => element.EnumerateObject().Count() != 0,
				_ => throw new JsonLogicException($"Cannot determine truthiness of `{element.ValueKind}`.")
			};
		}
```

I did some further tests and possibly identified another area where the expected result differs from what the JsonLogic.com playground suggests and that is with the reduce function.

```
private JsonElement ApplyRule(string logic, string data)
        {
            var rule = JsonSerializer.Deserialize<Rule>(logic);

            if (rule == null)
            {
                return new JsonElement();
            }

            return rule.Apply(data.ToJsonDocument().RootElement);
        }

[Test]
        public void TestReduce3()
        {
            var rule = "{\"reduce\": [\r\n        [\r\n          { \"var\": \"data.r\" },\r\n          { \"var\": \"data.t\" },\r\n          { \"var\": \"data.v\" }\r\n        ],\r\n        {\r\n          \"\\u002B\": [\r\n            { \"var\": \"accumulator\" },\r\n            { \"if\": [{ \"var\": \"current.0\" }, 1, 0] }\r\n          ]\r\n        },\r\n        0\r\n      ]}";
            var data = "{\"data\":{\"r\":[{\"tg\":\"140539006\"}]}}";

            var result = ApplyRule(rule, data);
			JsonAssert.AreEquivalent(1, result);
        }
```

> {"reduce": [
>         [
>           { "var": "data.r" },
>           { "var": "data.t" },
>           { "var": "data.v" }
>         ],
>         {
>           "\u002B": [
>             { "var": "accumulator" },
>             { "if": [{ "var": "current.0" }, 1, 0] }
>           ]
>         },
>         0
>       ]}

> {"data":{"r":[{"tg":"140539006"}]}}

Thanks
Jan

**Comment by gregsdennis** [comment] 2021-12-12 08:06
@JanKnipp what are you expecting with that last example, and how does that differ from what you're getting?

**Comment by JanKnipp** [comment] 2021-12-12 15:25
@gregsdennis The jsonlogic(.net) playground suggests that it should result in 1 (and that was my expectation) but it results in being 0.

**Comment by gregsdennis** [comment] 2021-12-13 09:07
Thanks.  I've pushed the changes to json-everything.net.  Hopefully that gets you a bit closer.  Still waiting on a response from @jwadhams.

**Comment by gregsdennis** [comment] 2021-12-13 09:19
I think your last example has more to do with the `current.0` than the logic processing itself.  I'm not sure if that expression is resolving properly.

**Comment by gregsdennis** [comment] 2021-12-19 06:58
Yeah, I've confirmed that `current.0` also doesn't process as expected.  This is likely because internally I convert it to a JSON Pointer `/current/0` which then doesn't resolve against `{"current":{"var":"data.v"},"accumulator":0}`.  `/current` exists, but `/0` is looking for either a property named `0` or the first index in an array, neither of which exist, so the pointer returns `null`.

`null` is then translated to a number `0` in `.Numberify()` for all three data items, and these are summed to give... 0.

**Comment by gregsdennis** [comment] 2021-12-19 07:51
I think I figured out what's going on in that last example.

```json
{
  "reduce": [
    [{ "var": "data.r" }, { "var": "data.t" }, { "var": "data.v" }],
    {
      "+": [
        { "var": "accumulator" },
        { "if": [{ "var": "current.0" }, 1, 0] }
      ]
    },
    0
  ]
}

{"data":{"r":[{"tg":"140539006"}]}}
```

While debugging, I found that when evaluating `{ "var": "current.0" }`, the `reduce` context is `{"current":{"var":"data.r"},"accumulator":0}`.  Evaluating `current.0` against this correctly produces `null`.

But what I think is happening on their site is that the values in the array are being recognized as rules and evaluated _before_ they're included in the iteration.  The site doesn't say anything about treating data as a rule, so I'll open an issue for this as well.

**Comment by gregsdennis** [comment] 2022-01-13 06:27
I'm not getting any further response.  I think I'm just going to try to emulate their behavior and be done with this.

**Comment by gregsdennis** [comment] 2022-02-08 01:13
We got a response from JsonLogic, but upon revisiting it, it seems that my implementation is returning `true` now.  I had added a `RuleCollection` class which in essense is an array of rules that is evaluated as a rule.  I think this did it.

**Closed by gregsdennis** 2022-02-08 01:13 UTC
Labels: bug, external blocker
