### ISSUE TITLE
bundling seems to no longer work

### ISSUE THREAD

**Issue by ItsVeryWindy** [gregsdennis/json-everything#208] opened 2022-01-25 14:15 UTC
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 2.0.0

**Describe the bug**
With 1.x one thing that I used to be able to do is embed one schema into another with the schema builder. The schema that got embedded had an id and also had references. In 1.x those references would resolve using the id of the embedded schema, but in 2.x they attempt to resolve using the id of the schema it's embedded in which causes the resolution to fail.

As described in https://json-schema.org/understanding-json-schema/structuring.html#bundling seems to dictate what the intended behaviour should be.

**To Reproduce**

**Expected behavior**
Behave the same way as before.

**Additional context**
Doing a bit of debugging in the IdKeyword I did note that `NavigatedByDirectRef` was true which seems to be why the url didn't get updated, but I don't know enough to understand what that is used for.

**Comment by gregsdennis** [comment] 2022-01-26 08:47
I think this is a duplicate of your other issue #207.  I'm going to close this and track it there.

**Comment by gregsdennis** [comment] 2022-02-01 18:32
@ItsVeryWindy you mentioned this still isn't fixed. I'm reopening.  Do you think you can devise a replicating test case?

**Comment by ItsVeryWindy** [comment] 2022-02-04 17:14
Ok, so this one took me longer to replicate as it wasn't as straightforward as I thought it was.

Two schemas are required.

One that will be referenced externally.
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://my-external-schema",
    "type": "object",
    "properties": {
        "first": {
            "type": "string"
        }
    }
}
```

Which is referenced by
```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://my-schema",
    "type": "object",
    "properties": {
        "first": {
            "$ref": "https://my-external-schema"
        },
        "second": {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "https://my-inner-schema",
            "type": "object",
            "properties": {
                "second": {
                    "$ref": "#/$defs/my-inner-ref"
                }
            },
            "$defs": {
                "my-inner-ref": {
                    "type": "string"
                }
            }
        }
    }
}
```

Which then validates
```json
{
    "first": {
        "first": "first"
    },
    "second": {
        "second": "second"
    }
}
```

When the schema is validated and hits that first reference the `RefKeyword` sets `NavigatedByDirectRef ` to `true`. When it hits the `IdKeyword` of the bundled schema this remains unchanged and so the Uri does not get updated.

**Comment by gregsdennis** [comment] 2022-02-09 04:36
Yep.  I've replicated the issue.  There's a test for it in branch `issue208_bundling`.

**Closed** 2022-02-09 07:54 UTC
Labels: bug
