### ISSUE TITLE
jsonnet as sister of json-e

### ISSUE THREAD

**Issue by He-Pin** [gregsdennis/json-everything#727] opened 2024-05-10 04:07 UTC
### Describe the functionality that isn't covered by this suite.

I think jsonnet is better than json-e for some cases

### Describe alternatives you've considered.

json-e

### Is there any other information you'd like to share regarding this functionality?

I think jsonnet is better for some cases

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment] 2024-05-10 04:09
Duplicate of #21.  I decided not to support it as it works require a custom parser rather than being supported by _System.Text.Json_.

**Closed** 2024-05-10 04:10 UTC
Labels: feature

**Comment by gregsdennis** [comment] 2024-05-10 04:16
Also, have you searched for "jsonnet" on Nuget? 😆

I don't think such a package could actually be found with all the JSON.net extensions!

**Comment by He-Pin** [comment] 2024-05-10 05:27
@gregsdennis lol, not actually:) thanks for that pointer.
